#! /usr/bin/env python3

import os, sys, hashlib

paths = []
for arg in sys.argv:
    for path, subdirs, files in os.walk(arg):
        for name in files:
            paths.append(os.path.join(path, name))
hashcat = b""
hasher = hashlib.md5()
for f in sorted(paths):
    with open(f,'rb') as file : 
        hashcat += file.read()

hasher.update(hashcat)